### ISSUE TITLE
Cosmetic - Secret Key/Log File Path non-existent error message is misleading

### ISSUE THREAD

**Issue by briamorr** [CiscoDevNet/intersight-powershell-utils#18]
Cosmetic - Secret Key/Log File Path non-existent error message is misleading

Error message in getWindowsOsInvToIntersight.ps1 when the Secret Key file and/or Log File Path not found is:
"[ERROR]: intersight_secret_file, and logfile_path must exist! Cannot Proceed..."

This is confusing to users to quickly diagnose where the issue is with their configuration file.

Suggest changing the error message from "_intersight_secret_file, **and** logfile_path must exist_" to _"intersight_secret_file, **or** logfile_path must exist_"

Or separating the if statement into two distinct error messages, one for secret key file and one for log file

**Comment by dsoper2** [comment]
Fixed with PR 19
